### ISSUE TITLE
Browser objects (window, HTMLElement...)

### ISSUE THREAD

**Issue by Fanda36** [Elderjs/elderjs#129]
Hi,

I'm trying to migrate from Sapper to Elder. My project works in Sapper. I use TypeScript in Svelte and for my libraries. I have troubles with some external libraries (like https://www.npmjs.com/package/streamsaver/v/1.2.0) and when I want to use `window` object. Before I run `npm run build` use `tsc` for compile *.ts to *.js (confit is bellow). Everything works well until I use window or HTMLElement. 

What is the correct way to use JS objects which are only in browser? I used in Sapper `if (typeof window !== 'undefined'){window(...)}` condition but it does not work in Elder.js.

Do you have an example how to import external libraries with `window` or how to use `window`?

Sapper doc: https://sapper.svelte.dev/docs#Server-side_rendering

Thank you.

component source code:
```html
<script lang="ts">
  import { DownloaderHelper } from '../../components/_library/helpers/DownloaderHelper';
  
  let downloadHelper = new DownloadHelper();
(...)
```

library source code:
```typescript
export class DownloaderHelper {
    async downloadURI(filename?: string): Promise<boolean> {
        if (this.canceled) {
            return false;
        }

        let resp = true;
        const localThis = this;
        if (!filename) {
            filename = this.filename;
        }
        if (!filename) {
            filename = "file";
        }

        // svelte - only on client
        if (typeof window !== 'undefined') {
            const streamSaver = require('streamsaver') // <------------- using external library
```

Error:

```js
{
  request: {
    slug: 'simple1',
    route: 'convert',
    type: 'build',
    permalink: '/simple1/'
  },
  errors: [
    {
      stack: "TypeError: Cannot read property 'HTMLElement' of undefined\n" +
        '    at t (/home/fanda/Documents/Vyvoj/frontend/___ELDER___/compiled/ConvertFileHolder-4bc67359.js:1:53741)\n' +
        '    at /home/fanda/Documents/Vyvoj/frontend/___ELDER___/compiled/ConvertFileHolder-4bc67359.js:1:57480\n' +
        '    at Object.exports.createCommonjsModule (/home/fanda/Documents/Vyvoj/frontend/___ELDER___/compiled/_commonjsHelpers-f805bdb9.js:1:370)\n' +
        '    at Object.<anonymous> (/home/fanda/Documents/Vyvoj/frontend/___ELDER___/compiled/ConvertFileHolder-4bc67359.js:1:53648)\n' +
        '    at Module._compile (internal/modules/cjs/loader.js:1063:30)\n' +
        '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)\n' +
        '    at Module.load (internal/modules/cjs/loader.js:928:32)\n' +
        '    at Function.Module._load (internal/modules/cjs/loader.js:769:14)\n' +
        '    at Module.require (internal/modules/cjs/loader.js:952:19)\n' +
        '    at require (internal/modules/cjs/helpers.js:88:18)',
      message: "Cannot read property 'HTMLElement' of undefined"
    }
```

frontend/___ELDER___/compiled/ConvertFileHolder-4bc67359.js:1:53741:
```js
(...){const e="object"==typeof window?window:this;e.HTMLElement||console.warn("streamsaver is meant to run on browsers main thread");(...)
                                                  ^^^^ error this source is from streamsaver library
```

my tsconfig.json (for my libraries only, not for Svelte components):
```json
{
  "compilerOptions": {
    "target": "es2019",
    "module": "commonjs",
    "lib": [
      "es2020",
      "dom"
    ],
    "outDir": "./src/components/_library",
    "skipLibCheck": true,
    "strict": false,
    "esModuleInterop": true
  },
  "include": [
    "./src/components/_library/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}
```

**Comment by nickreese** [comment]
`process.env.componentType === 'server'` and `process.env.componentType === 'browser'` will achieve what you're looking on the default template.
