### ISSUE TITLE
Shortcodes in hydrate client component (static content in hydrated components)

### ISSUE THREAD

**Issue by Fanda36** [Elderjs/elderjs#137]
Hi,

I am trying to do translation. I'd like to replace all all id's to translated string. I did an helper which generate id's and can add additional data.

```html
<h2 class="vf-h2 center">{T.gST('convert.how-use.head', `How does it work?`)}</h2>
```
is generated to
```html
<h2 class="vf-h2 center">__t__convert.how-use.head:eyJkZWZhdWx0IjoiSG93IGRvZXMgaXQgd29yaz8ifQ==</h2>
```
then it is replaced via html hook (there are adicionalita data for example variable for passing to translation) to final string.

Everything works in static components. But I do not known how to add static content into hydrate component (`hydrate-client={{}}`). It could be nice to apply shortcodes replace function to all components before there is anything to do (it will replace all shortcodes in all components). Or add hook beforeComponentCompiled, then users will be able to do some string replace.

Or do you have idea how to add static content into hydrated component during compiling (in my case replace translation id's to translated text)?

Thank you.

**Comment by kiuKisas** [comment]
Running into the same issue, currently thinking about it..

**Comment by nickreese** [comment]
Look at the shortcode helper. 

`{ @html helpers.shortcode({name: 'box', props: {class: "yellow"}, content: "content string here" }) } `

**Comment by Fanda36** [comment]
@nickreese  I did not found a way how to use helpers in non route component. I did an example of my problem:

```html
Route component (routes/time/Time.svelte)
<script lang="ts">
import { TranslateHelper as T } from '../../plugins/elderjs-plugin-translate/TranslateHelper';
 /** some code*/
</script>

<Headline
  title={data.title}
  description={data.description}  />

<!-- this works me because this component is not hydrated and its generated during build -->
{T.gST('time.foo', `Foo:`)}

<Clock hydrate-client={{}} />
```

```html
Component (components/Clock.svelte)
<script lang="ts">
  import { onMount } from 'svelte';
  import { TranslateHelper as T } from '../../plugins/elderjs-plugin-translate/TranslateHelper';

  let time = new Date();

  onMount(() => {
    const interval = setInterval(() => {
      time = moment().tz('America/Los_Angeles').format();
    }, 1000);

    return () => {
      clearInterval(interval);
    };
  });
</script>

<!-- STATIC CONTENT WHICH NEED TO BE GENERATED DURING BUILD TIME -->
<!-- DURING BUILD TIME I KNOWN REQUEST OBJECT AND DATA SO I CAN RESOLVE METHOD BELOW  -->
{T.gST('clock.current-time', `Current time is:`)}
<!-- if this component will be not hydrated then it will generate translation id + data in base64 for easy parsing during html hook __t__clock.current-time:eyJkZWZhdWx0IjoiSG93IGRvZXMgaXQgd29yaz8ifQ== -->
<!-- then html hook will transform __t__... into translated string -->

<!-- I do not known ho I can generate static content for hydrated components -->

<p>{time}</p>
```

```js
//my plugin index.ts

// ....

hooks: [
    {
      hook: 'html',
      name: 'replaceStaticTranslations',
      description: `Replace __t__`,
      priority: 50,
      run: async ({ plugin, request, htmlString, settings }) => {

        htmlString = htmlString.replace(/__t__([\w\/.:=-]+)/g, (matched) => {
           // ....
        }
        // ....
      }
    }
];
```



Possible solution:

Could be shortcode or maybe better some function which will be replaced during build time with return value. For example:

```html
hydrated/not hydrated component in routes or components folder

{{__myFunction("param1", {param2: "aa"})__}}
```

```js
customReplace.js (or some better name)

// function will get params from component and Elder objects
myFunction(param1, param2, route, data, helpers){
  // do something
  return "<p>foo</p>";
}
```

Result after compile time:
```html
hydrated/not hydrated component after compile

<p>foo</p>
```

**Comment by Fanda36** [comment]
I dig deeper into Elder code and maybe found a solution. Components are compiled (with preprocessor and then with compile functions) here https://github.com/Elderjs/elderjs/blob/902d7f4352d50091f10d38314141462f112895a4/src/rollup/rollupPlugin.ts#L282

If I can get elder objects (`request`, `settings`...)  at this line, then could be possible pass this object to Svelte preprocessor and replace what is needed.

**Comment by nickreese** [comment]
The easiest way to get shortcodes / helpers into a component dueing SSR is to just pass the  `helpers` Object deeper. As shortcodes are only processed during rendering of the html they can’t be used within `onMount` Or other non-ssr contexts because allowing for that would leak tons of information you wouldnt want on the client.

**Comment by nickreese** [comment]
Also regarding using the preprocessor this runs async from the code so we can’t always be confident the `settings` Would match and the `request` Object doesnt exist yet.

**Comment by nickreese** [comment]
Why not just try using the `helpers.shortcode` And passing the value you need into the hydrated component as a prop?

**Comment by Fanda36** [comment]
@nickreese I tried `helpers.shortcode` first. But I can not found a way how to use it in included components.

Route component
```html
<script lang="ts">
  import Clock from '../../components/worldtime/Clock.svelte';

  export let helpers;
</script>

<!-- ROOT COMPONENT THIS WORKS -->
{@html helpers.shortcode({ name: 'simple', props: { background: 'blue' }, content: 'Inner content' })}

<Clock hydrate-client={{ helpers }} hydrate-options={{ preload: true }} />

```

Clock.svelte
```html
<script lang="ts">
  import { onMount } from 'svelte';

  export let helpers;

  let time = new Date();

  onMount(() => {
    const interval = setInterval(() => {
      time = moment().tz('America/Los_Angeles').format();
    }, 1000);

    return () => {
      clearInterval(interval);
    };
  });
</script>

<!-- NOT WORKING -->
{@html helpers.shortcode({ name: 'simple', props: { background: 'blue' }, content: 'Inner content' })}

<p>{time}</p>

```

```
/worldtime/ [
  TypeError: helpers.shortcode is not a function
      at /home/fanda/Documents/Vyvoj/frontend/___ELDER___/compiled/Clock-26f12bb3.js:7287:11
      at $$render (/home/fanda/Documents/Vyvoj/frontend/___ELDER___/compiled/index-0c372904.js:1343:22)
      at render (/home/fanda/Documents/Vyvoj/frontend/___ELDER___/compiled/index-0c372904.js:1351:26)
      at /home/fanda/Documents/Vyvoj/frontend/node_modules/@elderjs/elderjs/build/utils/svelteComponent.js:23:44
      at Object.mountComponentsInHtml [as default] (/home/fanda/Documents/Vyvoj/frontend/node_modules/@elderjs/elderjs/build/partialHydration/mountComponentsInHtml.js:46:77)
      at Object.templateComponent (/home/fanda/Documents/Vyvoj/frontend/node_modules/@elderjs/elderjs/build/utils/svelteComponent.js:36:55)
      at buildPage (/home/fanda/Documents/Vyvoj/frontend/node_modules/@elderjs/elderjs/build/utils/Page.js:43:40)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Object.run (/home/fanda/Documents/Vyvoj/frontend/node_modules/@elderjs/elderjs/build/hooks/index.js:83:34)
      at async /home/fanda/Documents/Vyvoj/frontend/node_modules/@elderjs/elderjs/build/utils/prepareRunHook.js:46:44
]
```

Clock-26f12bb3.js:7287:11
```js
	if ($$props.helpers === void 0 && $$bindings.helpers && helpers !== void 0) $$bindings.helpers(helpers);

	return `
${helpers.shortcode({            <------------- error
		name: "simple",
		props: { background: "blue" },
		content: "Inner content"
	})}

<p>${index.escape(time)}</p>`;
});
```
