### ISSUE TITLE
[from 1.4 to 1.5.2][linux] Editing layout or page resulting in elder.js crashing

### ISSUE THREAD

**Issue by kiuKisas** [Elderjs/elderjs#198]
### Step to reproduce
- `yarn run dev`
-  edit a file

#### Layout 
- website doesn't update, if I reload my page, I get this message in my shell
```
Error: ENOENT: no such file or directory, open '/home/equinox/Programming/opo/website/public/_elderjs/assets/svelte-896aca30.css'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:147:14
    at FSReqCallback.oncomplete (fs.js:171:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/equinox/Programming/opo/website/public/_elderjs/assets/svelte-896aca30.css'
}
> Elder.js process exited with code 1

```
--> need to restart to see my change

### Route
--> same result

### Components
It works !

### with esbuild
-> Layout: doesn't update my page, even if I reload
-> route/MyRoute.svelte: same error as the previsous one
-> components/MyComponents.svelte: It works !

**Comment by elmarsto** [comment]
I've got this too.

**Comment by elmarsto** [comment]
Git Bisect FTW. 

I'd added `svelte-octicons`. For whatever reason, when this package is added and icons are used from it, the error recurs. When it is removed, the error stops. 

I'm a svelte and elderjs newb so all I've got to offer is this humble issue ticket. If anyone else has this error and sees this: try to remove recently-added third-party packages. Elderjs and svelte-octicons are not friends, and I suspect there are other 3p packages in the same boat.
