### ISSUE TITLE
Question: around testing boundaries

### ISSUE THREAD

**Issue by thisislawatts** [Elderjs/elderjs#73]
https://github.com/Elderjs/elderjs/blob/b19dba3d336a62311c664d960249f7564d4716d9/src/routes/__tests__/routes.spec.ts#L3-L7

Hey @halafi, would you be able to help me understand what value we get from reimplementing `path` here?

**Comment by halafi** [comment]
Hi,
to be honest, probably not much, I just tried to keep unit tests as isolated as possible - so no external change would break a single test - that's anyway not kept up 100%.

In hindsight I probably would/will not chose to mock it again, so feel free to drop that.

**Comment by thisislawatts** [comment]
👍 Thanks for clarifying @halafi, appreciate the ambition here but I am worried that creating mock implementations of system internals means we end up creating a test environment which does not accurately represent the target execution environment.

**Comment by thisislawatts** [comment]
It looks like removing it from `routes.spec.ts` is painless but some of the other tests which are stubbing `path` do not pass locally when using the instance of `path` from the node distribution. 🤔

**Comment by thisislawatts** [comment]
Working on a branch here:
https://github.com/Elderjs/elderjs/compare/master...thisislawatts:test/remove-mocks-for-nodejs-internals?expand=1

**Comment by thisislawatts** [comment]
@halafi for example this looks like a legitimate test failure which was being masked by the mock implementation:
`../elderjs/src/__tests__/hooks.spec.ts`
```
TypeError: The "path" argument must be of type string. Received undefinedTypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
      269 |     run: async ({ settings, request, htmlString, errors }) => {
      270 |       if (settings.build) {
    > 271 |         const file = path.resolve(settings.distDir, `.${request.permalink}/index.html`);
          |                           ^
      272 |         try {
      273 |           fs.outputFileSync(file, htmlString);
      274 |         } catch (e) {

      at Object.run (src/hooks.ts:271:27)
      at Object.<anonymous> (src/__tests__/hooks.spec.ts:159:18)
```
